
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ data }) {
  console.log(data)
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <main className={styles.main}>
      <Link legacyBehavior href="/">
             <a>Volver al inicio</a>
          </Link>
          <Link  legacyBehavior href={"/contact/numbers"}>
            <a>Numbers</a>
          </Link>
          <Link legacyBehavior href={"/about"}>
            <a>about</a>
          </Link>
          <h1>Lista de blogs</h1>
          {data.map(({id, title, body}) => (
            <div key={id} style={{margin: 5, background: '#DEE4E5', width: '90%', borderRadius: '2px'}}>
             <Link legacyBehavior href={`/contact/${id}`}>
              <a style={{margin: 5, textAlign:'center'}}>
                {id}---{title}
              </a>
              </Link> 
              <p style={{padding: '1rem', textAlign:'center'}}>{body}</p>
            
            </div>
          ))}
      </main> 
    </>
  )
}

export async function getStaticProps() {
  try {
    const res = await fetch('https://jsonplaceholder.typicode.com/posts/')
    const data = await res.json();
    return{
      props: {
        data,
      }
    }
  } catch (error) {
    console.log(error)
  }
}
